version: "3.8"

services:

  pgdb:
    container_name: pgdb
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - from-orm_db-volume:/var/lib/postgresql/data

volumes:
  from-orm_db-volume:
    external: true