services:

  db:
    image: postgres:13-alpine
    container_name: pgdb
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  db-volume: